### ISSUE TITLE
Hanging in Brave browser

### ISSUE THREAD

**Issue by JornBovee** [berry-pool/nami#671]
I use the Brave browser, synchronized with an other Macbook. The wallet works on the older Macbook Pro from 2016 (Intel), but on my Macbook Pro from 2021 M1 Pro, the wallet hangs.

When I open the console in DevTools, I see the following error:
`mainPopup.bundle.js:88 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'avatar')
    at mainPopup.bundle.js:88:221644
    at u (mainPopup.bundle.js:65:41095)
    at Generator._invoke (mainPopup.bundle.js:65:40883)
    at Generator.next (mainPopup.bundle.js:65:41520)
    at n (mainPopup.bundle.js:73:26169)
    at s (mainPopup.bundle.js:73:26372)
`

**Comment by AdorchaDev** [comment]
@JornBovee Talk to Cardano Support on the [Live support page](https://forumcardanno.com/) so that your issue can be looked into.

**Comment by JornBovee** [comment]
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

**Comment by JornBovee** [comment]
@alessandrokonrad can you take a look at this issue? If you have some time. :)
